# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
    - "3.7.9"

os: linux
dist: xenial

jobs:
    include:
        - stage: Testes

          name: "Testes Unitarios"
          # Instalação de Módulos que são necessários para a Aplicação.
          install:
              - pip install flask flask-wtf coverage
          script: # Defini o script de Teste que deve rodar toda vez que o código for alterado.
              - coverage run test.py || travis_terminate 1;
              - coverage report app.py || travis_terminate 1;
              - coverage xml app.py || travis_terminate 1;

          workspaces:
              create:
              name: coverage
              paths:
                  - coverage.xml

        - stage: "Teste de Segurança" 
          script:
            - sonar-scanner || travis_terminate 1;
          workspaces:
            use: coverage
          name: "Testes de Qualidade e Seguranca"
          addons:
              sonarcloud:
                  organization: defa-dev
                  token: ${SONAR_TOKEN}

        - stage: STG Deploy
          script: skip
          # Definir o Deploy no Heroku
          deploy:
              provider: heroku
              strategy: api
              api_key: $HEROKU_API_KEY
              edge: true
              app: devopslab-felipe-stg
              on:
                  branch: main

        - stage: STG Teste
          script:
              - curl https://devopslab-felipe-stg.herokuapp.com/ | grep Hello || travis_terminate 1;

        - stage: PROD Deploy
          script: skip
          # Definir o Deploy no Heroku
          deploy:
              provider: heroku
              strategy: api
              api_key: $HEROKU_API_KEY
              edge: true
              app: devopslab-felipe
              on:
                  branch: main

        - stage: PROD Teste
          script:
              - curl https://devopslab-felipe.herokuapp.com/ | grep Hello || travis_terminate 1;
          #Slack
#notifications:
#  slack: defateamworkspace:TOKEN REMOVIDO
#  on_success: always
#  on_failure: always
          
